services:
  backend:
    image: learnesia-backend-prod
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    expose:
      - "8000"
    restart: always

  frontend:
    image: learnesia-frontend-prod
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
