services:
  backend:
    image: learnesia-backend-prod
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    environment:
      - DEBUG=False
    expose:
      - "8000"
    restart: always

  frontend:
    image: learnesia-frontend-prod
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    environment:
      - API_URL=http://backend:8000/api
      - NEXT_PUBLIC_API_URL=/api
      - NEXT_PUBLIC_SITE_URL=https://learnesia.co.id
    depends_on:
      - backend
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - frontend
    restart: unless-stopped
