# Generated by Django 6.0.1 on 2026-01-13 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnesia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_title', models.CharField(max_length=255)),
                ('reference_url', models.URLField(blank=True, null=True)),
                ('reference_type', models.CharField(choices=[('link', 'Link'), ('document', 'Document'), ('video', 'Video')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='learnesia.lesson')),
            ],
        ),
    ]
