# Generated by Django 6.0.1 on 2026-01-13 02:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnesia', '0002_lessonreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_learning_objectives',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_learning_objectives',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list),
        ),
    ]
