# Generated by Django 6.0.1 on 2026-01-14 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnesia', '0003_course_course_learning_objectives_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_content',
            field=models.TextField(blank=True),
        ),
    ]
