# Generated by Django 6.0.1 on 2026-01-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnesia', '0004_alter_lesson_lesson_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('template', 'Template'), ('draft', 'Draft'), ('published', 'Published')], db_index=True, default='template', max_length=20),
        ),
    ]
