# Generated by Django 6.0.1 on 2026-01-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnesia', '0005_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
