# Generated by Django 6.0.1 on 2026-02-06 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnesia', '0007_quiz_quizquestion_questionoption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='lesson',
            field=models.ForeignKey(db_column='lesson_id', on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='learnesia.lesson', unique=True),
        ),
    ]
