# Generated by Django 6.0.1 on 2026-02-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnesia', '0009_course_course_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
