# Generated by Django 6.0.1 on 2026-02-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnesia', '0010_lesson_lesson_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='estimated_time',
            field=models.PositiveIntegerField(default=0, help_text='Estimated time to complete in minutes'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='estimated_time',
            field=models.PositiveIntegerField(default=0, help_text='Estimated time to complete in minutes'),
        ),
    ]
