# Generated by Django 6.0.1 on 2026-02-25 07:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnesia', '0011_course_estimated_time_lesson_estimated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list),
        ),
    ]
