# Generated by Django 6.0.1 on 2026-02-25 07:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnesia', '0012_course_course_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=list, max_length=255)),
        ),
    ]
