# Generated by Django 6.0.1 on 2026-03-03 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnesia', '0013_alter_course_course_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=5, help_text='Rating from 1 to 5')),
                ('comment', models.TextField(blank=True, null=True)),
                ('user_identifier', models.CharField(blank=True, help_text='Optional user ID or anonymous session ID', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(db_column='lesson_id', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='learnesia.lesson')),
            ],
            options={
                'verbose_name_plural': 'lesson feedbacks',
                'db_table': 'lesson_feedback',
                'indexes': [models.Index(fields=['lesson'], name='idx_feedback_lesson')],
            },
        ),
    ]
