# Generated by Django 6.0.1 on 2026-03-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnesia', '0014_lessonfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
