# Generated by Django 6.0.1 on 2026-06-04 03:14

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnesia', '0017_quiz_block_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('link', 'Link'), ('document', 'Document'), ('video', 'Video')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='course_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list),
        ),
        migrations.CreateModel(
            name='LessonCitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('citation', 'Citation'), ('supplementary', 'Supplementary')], max_length=20)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citations', to='learnesia.contentblock')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='learnesia.lesson')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_citations', to='learnesia.reference')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
